jobs:
  build:
    name: Build
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties', 'project/Dependencies.scala') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: "java ${{ matrix.scala}} setup"
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: "${{ matrix.scala}}"
      - run: "sbt \"++${{ matrix.scala}} test\""
    strategy:
      matrix:
        java:
          - '8.0.232'
          - '11.0.5'
        scala:
          - '2.11.12'
          - '2.12.11'
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties', 'project/Dependencies.scala') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: java 11 setup
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: '11'
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
name: Greeting
on:
  pull_request: {}
  push: {}
