name: main
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: generate cache key
        run: |
          shasum build.sbt \
          project/plugins.sbt \
          project/build.properties \
          project/Dependencies.scala > gha.cache.tmp
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/setup-java@v1
        with:
          java-version: "11.0.5"
          architecture: x64
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8.0.232", "11.0.5"]
        scala: ["2.11.12", "2.12.11"]
    steps:
      - uses: actions/checkout@master
      - name: generate cache key
        run: |
          shasum build.sbt \
          project/plugins.sbt \
          project/build.properties \
          project/Dependencies.scala > gha.cache.tmp
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: sbt "++${{ matrix.scala}} test"
  publish-snapshot:
    name: publish-snapshot
    runs-on: ubuntu-latest
    needs: [build, checks]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: generate cache key
        run: |
          shasum build.sbt \
          project/plugins.sbt \
          project/build.properties \
          project/Dependencies.scala > gha.cache.tmp
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/setup-java@v1
        with:
          java-version: "11.0.5"
          architecture: x64
      - run: .github/scripts/gpg-setup.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
      - run: sbt +publishSigned
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build, checks]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - name: generate cache key
        run: |
          shasum build.sbt \
          project/plugins.sbt \
          project/build.properties \
          project/Dependencies.scala > gha.cache.tmp
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/setup-java@v1
        with:
          java-version: "11.0.5"
          architecture: x64
      - run: .github/scripts/gpg-setup.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
      - run: sbt +publishSigned sonatypeBundleRelease ghpagesPushSite
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
