jobs:
  build:
    name: Check Frozen Imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4
        with:
          version: "1.42.0"
      - name: dhall freeze
        run: dhall freeze --all ./package.dhall

name: Test
on:
  push: {}
